"""Literature ablations keep training isolation, bounded gates and pure-rule export."""
import json

import numpy as np
import pytest
from sklearn.tree import DecisionTreeRegressor
import torch

from analysis.eda import load_abalone
from experiments.run_abalone import BASE
from models.rrl.abalone import (
    cut_points, export_rules, fit, predict, prepare, project_fanin, rule_diagnostics,
)
from models.rrl.abalone_refine import refit, predict_refit, graph_with_head, predict_graph


def samples():
    torch.set_num_threads(1)
    frame = load_abalone().sample(n=240, random_state=731)
    return frame.iloc[:192].copy(), frame.iloc[192:].copy()


def test_legacy_paired_predictions_unchanged():
    train, valid = samples()
    config = dict(BASE, epochs=6, structure='3@5', threshold='quantile', paired_init=True, lr=.03)
    model, state, _ = fit(train, config, 17)
    # Captured before adding tree cuts/projection, not generated by the new path.
    expected = [9.53050422668457, 7.123019218444824, 10.564595222473145,
                9.53050422668457, 9.53050422668457, 8.162063598632812,
                9.53050422668457, 10.564595222473145, 9.53050422668457,
                9.53050422668457, 10.564595222473145, 10.564595222473145]
    assert np.allclose(predict(model, state, valid.iloc[:12]), expected, rtol=0, atol=1e-6)
    disabled, other, _ = fit(train, dict(config, max_fanin=None, monitor_rules=False), 17)
    assert state == other
    assert np.array_equal(predict(model, state, valid), predict(disabled, other, valid))


def test_tree_thresholds_match_recursive_sse_and_ignore_validation():
    train, valid = samples()
    changed = valid.copy()
    changed['Rings'] += 1000
    changed['Length'] *= 100
    config = dict(BASE, epochs=0, structure='5@4', threshold='tree', paired_init=True)
    model, state, _ = fit(train, config, 17, validation=valid)
    other, other_state, _ = fit(train, config, 17, validation=changed)
    assert state == other_state
    assert torch.equal(model.net.layer_list[0].cl, other.net.layer_list[0].cl)
    X, _ = prepare(train, state)
    X = X[:, len(state['categories'])-1:]
    cuts = model.net.layer_list[0].cl.numpy()
    assert cuts.shape == (5, X.shape[1]) and np.all(np.diff(cuts, axis=0) >= 0)
    for j in range(X.shape[1]):
        tree = DecisionTreeRegressor(criterion='squared_error', max_leaf_nodes=6,
                                     min_samples_leaf=.02, random_state=0).fit(X[:, j:j+1], train.Rings)
        splits = tree.tree_.threshold[tree.tree_.children_left != -1].astype('float32')
        assert len(splits) == 5
        assert np.array_equal(cuts[:, j], np.sort(splits))
    quantile, _, _ = fit(train, dict(config, threshold='quantile'), 17)
    for a, b in zip(model.net.parameters(), quantile.net.parameters()):
        assert torch.equal(a, b), 'Changing cuts must not change paired gate/readout initialization'


def test_tree_fallback_retains_budget_and_spreads_quantiles():
    X = np.arange(100, dtype=float)[:, None]
    y = (X[:, 0] >= 40).astype(float)
    actual = cut_points(X, y, 5, 'tree', tree_min_leaf=.4).numpy()[:, 0]
    pool = np.quantile(X[:, 0], np.arange(1, 6)/6)
    # 39.5 is the sole tree split. Four stratum-midpoint quantiles spread across
    # the five-element remaining pool instead of just taking its lowest four.
    assert np.array_equal(actual, np.sort(np.r_[39.5, pool[[0, 1, 3, 4]]]).astype('float32'))
    # No learned splits: deterministic quantiles, not target-informed guessing.
    assert np.array_equal(cut_points(X, np.zeros(100), 5, 'tree').numpy()[:, 0], pool.astype('float32'))
    constant = cut_points(np.ones((100, 2)), y, 5, 'tree').numpy()
    assert constant.shape == (5, 2) and np.array_equal(constant, np.ones((5, 2)))


def test_fanin_projection_preserves_positive_inactive_gates_and_gradients():
    train, _ = samples()
    model, _, _ = fit(train, dict(BASE, epochs=0, structure='3@4'), 17)
    parts = [model.net.layer_list[1].con_layer, model.net.layer_list[1].dis_layer]
    with torch.no_grad():
        for part in parts:
            part.W.fill_(.2)
            part.W[:3] = torch.tensor([.9, .8, .7])[:, None]
    project_fanin(model, 2)
    for part in parts:
        assert torch.equal((part.W > .5).sum(0), torch.full((part.n,), 2))
        assert torch.all(part.W[:2] > .5) and torch.all((part.W[2] > 0) & (part.W[2] < .5))
        assert torch.all(part.W[3:] == .2), 'Projection must not freeze or perturb inactive candidates'
        inputs = torch.stack([torch.zeros(part.input_dim), torch.ones(part.input_dim)])
        part(inputs).sum().backward()
        assert torch.isfinite(part.W.grad).all() and torch.all(part.W.grad[2].abs() > 0)
        with torch.no_grad():
            part.W[2] = .99  # A subsequent optimizer update can re-open a demoted edge.
    project_fanin(model, 2)
    for part in parts:
        assert torch.all(part.W[2] > .5) and torch.all(part.W[1] < .5)
        with torch.no_grad():
            part.W.fill_(.2)
            part.W[:3] = .8
    project_fanin(model, 2)
    for part in parts:
        assert torch.all(part.W[:2] == .8) and torch.all(part.W[2] < .5)
        assert torch.all(part.W[3:] == .2), 'Equal-weight ties retain the earliest input rows'
    for invalid in (0, -1, 1.5, True):
        with pytest.raises(ValueError, match='max_fanin'):
            project_fanin(model, invalid)


@pytest.mark.parametrize('structure', ['3@6', '3@6@4'])
def test_cap_survives_monitoring_best_restore_export_and_checkpoint(tmp_path, structure):
    train, valid = samples()
    single = structure.count('@') == 1
    config = dict(BASE, epochs=4, structure=structure, threshold='tree', lr=.03,
                  paired_init=single, init_literals=4 if single else 0, max_fanin=2,
                  monitor_rules=True, rule_head_alpha=.1, stop_patience=1,
                  monitor_every=1, min_delta=1e6)
    history = []
    model, state, args = fit(train, config, 17, validation=valid, history=history)
    assert state['best_epoch'] == 1 and state['epochs_run'] == 2 and state['max_fanin'] == 2
    assert all(row['max_fanin_observed'] <= 2 for row in history)
    if single:
        for kind in ['conjunction', 'disjunction']:
            assert all(len(gates) == 2 for gates in state['initial_gates'][kind])
    X, _ = prepare(train, state)
    stats = rule_diagnostics(model, X)
    assert all(history[0][key] == value for key, value in stats.items())
    assert stats['distinct_nonconstant_rules'] <= stats['nonconstant_rules']
    head = refit(model, state, train, 'rules', .1)
    graph = graph_with_head(export_rules(model, state, train, tmp_path/'rules'), head)
    graph = json.loads(json.dumps(graph))
    for layer in graph['layers']:
        for kind in ['conjunction', 'disjunction']:
            assert np.asarray(layer[kind]).sum(0).max() <= 2
    assert head['linear_weights'] == [] and head['hinge_knots'] is None
    assert np.allclose(predict_refit(model, state, valid, head), predict_graph(graph, valid), atol=1e-5)
    checkpoint = tmp_path/'model.pth'
    torch.save(dict(weights=model.net.state_dict(), args=args, state=state, head=head), checkpoint)
    saved = torch.load(checkpoint, weights_only=False)
    restored = type(model)(**saved['args'])
    restored.net.load_state_dict(saved['weights'])
    assert rule_diagnostics(restored, X) == stats
    assert np.array_equal(predict_refit(model, state, valid, head),
                          predict_refit(restored, saved['state'], valid, saved['head']))
